// Code generated by protoc-gen-go.
// source: sajari/engine/value.proto
// DO NOT EDIT!

package sajari_engine

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Value is a repesentation data of columnular data for a document.
type Value struct {
	// Types that are valid to be assigned to Value:
	//	*Value_Null
	//	*Value_Single
	//	*Value_Repeated_
	Value isValue_Value `protobuf_oneof:"value"`
}

func (m *Value) Reset()                    { *m = Value{} }
func (m *Value) String() string            { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()               {}
func (*Value) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type isValue_Value interface {
	isValue_Value()
}

type Value_Null struct {
	Null bool `protobuf:"varint,1,opt,name=null,oneof"`
}
type Value_Single struct {
	Single string `protobuf:"bytes,2,opt,name=single,oneof"`
}
type Value_Repeated_ struct {
	Repeated *Value_Repeated `protobuf:"bytes,3,opt,name=repeated,oneof"`
}

func (*Value_Null) isValue_Value()      {}
func (*Value_Single) isValue_Value()    {}
func (*Value_Repeated_) isValue_Value() {}

func (m *Value) GetValue() isValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Value) GetNull() bool {
	if x, ok := m.GetValue().(*Value_Null); ok {
		return x.Null
	}
	return false
}

func (m *Value) GetSingle() string {
	if x, ok := m.GetValue().(*Value_Single); ok {
		return x.Single
	}
	return ""
}

func (m *Value) GetRepeated() *Value_Repeated {
	if x, ok := m.GetValue().(*Value_Repeated_); ok {
		return x.Repeated
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Value) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Value_OneofMarshaler, _Value_OneofUnmarshaler, _Value_OneofSizer, []interface{}{
		(*Value_Null)(nil),
		(*Value_Single)(nil),
		(*Value_Repeated_)(nil),
	}
}

func _Value_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Value)
	// value
	switch x := m.Value.(type) {
	case *Value_Null:
		t := uint64(0)
		if x.Null {
			t = 1
		}
		b.EncodeVarint(1<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case *Value_Single:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Single)
	case *Value_Repeated_:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Repeated); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Value.Value has unexpected type %T", x)
	}
	return nil
}

func _Value_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Value)
	switch tag {
	case 1: // value.null
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &Value_Null{x != 0}
		return true, err
	case 2: // value.single
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Value = &Value_Single{x}
		return true, err
	case 3: // value.repeated
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Value_Repeated)
		err := b.DecodeMessage(msg)
		m.Value = &Value_Repeated_{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Value_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Value)
	// value
	switch x := m.Value.(type) {
	case *Value_Null:
		n += proto.SizeVarint(1<<3 | proto.WireVarint)
		n += 1
	case *Value_Single:
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Single)))
		n += len(x.Single)
	case *Value_Repeated_:
		s := proto.Size(x.Repeated)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Repeated values
type Value_Repeated struct {
	Values []string `protobuf:"bytes,1,rep,name=values" json:"values,omitempty"`
}

func (m *Value_Repeated) Reset()                    { *m = Value_Repeated{} }
func (m *Value_Repeated) String() string            { return proto.CompactTextString(m) }
func (*Value_Repeated) ProtoMessage()               {}
func (*Value_Repeated) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0, 0} }

func (m *Value_Repeated) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

func init() {
	proto.RegisterType((*Value)(nil), "sajari.engine.Value")
	proto.RegisterType((*Value_Repeated)(nil), "sajari.engine.Value.Repeated")
}

func init() { proto.RegisterFile("sajari/engine/value.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 174 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x92, 0x2c, 0x4e, 0xcc, 0x4a,
	0x2c, 0xca, 0xd4, 0x4f, 0xcd, 0x4b, 0xcf, 0xcc, 0x4b, 0xd5, 0x2f, 0x4b, 0xcc, 0x29, 0x4d, 0xd5,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x85, 0x48, 0xe9, 0x41, 0xa4, 0x94, 0x16, 0x32, 0x72,
	0xb1, 0x86, 0x81, 0xa4, 0x85, 0x44, 0xb8, 0x58, 0xf2, 0x4a, 0x73, 0x72, 0x24, 0x18, 0x15, 0x18,
	0x35, 0x38, 0x3c, 0x18, 0x82, 0xc0, 0x3c, 0x21, 0x09, 0x2e, 0xb6, 0xe2, 0xcc, 0xbc, 0xf4, 0x9c,
	0x54, 0x09, 0x26, 0x05, 0x46, 0x0d, 0x4e, 0x0f, 0x86, 0x20, 0x28, 0x5f, 0xc8, 0x9a, 0x8b, 0xa3,
	0x28, 0xb5, 0x20, 0x35, 0xb1, 0x24, 0x35, 0x45, 0x82, 0x59, 0x81, 0x51, 0x83, 0xdb, 0x48, 0x56,
	0x0f, 0xc5, 0x6c, 0x3d, 0xb0, 0xb9, 0x7a, 0x41, 0x50, 0x45, 0x1e, 0x0c, 0x41, 0x70, 0x0d, 0x52,
	0x4a, 0x5c, 0x1c, 0x30, 0x71, 0x21, 0x31, 0x2e, 0x36, 0xb0, 0x03, 0x8b, 0x25, 0x18, 0x15, 0x98,
	0x35, 0x38, 0x83, 0xa0, 0x3c, 0x27, 0x76, 0x2e, 0x56, 0x30, 0x2b, 0x89, 0x0d, 0xec, 0x72, 0x63,
	0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x21, 0x70, 0xab, 0xee, 0xd6, 0x00, 0x00, 0x00,
}
