// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sajari/engine/value.proto

package engine

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Value is a repesentation data of columnular data for a record.
type Value struct {
	// Types that are valid to be assigned to Value:
	//	*Value_Null
	//	*Value_Single
	//	*Value_Repeated_
	Value                isValue_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c929259feb9628e, []int{0}
}

func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (m *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(m, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

type isValue_Value interface {
	isValue_Value()
}

type Value_Null struct {
	Null bool `protobuf:"varint,1,opt,name=null,proto3,oneof"`
}

type Value_Single struct {
	Single string `protobuf:"bytes,2,opt,name=single,proto3,oneof"`
}

type Value_Repeated_ struct {
	Repeated *Value_Repeated `protobuf:"bytes,3,opt,name=repeated,proto3,oneof"`
}

func (*Value_Null) isValue_Value() {}

func (*Value_Single) isValue_Value() {}

func (*Value_Repeated_) isValue_Value() {}

func (m *Value) GetValue() isValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Value) GetNull() bool {
	if x, ok := m.GetValue().(*Value_Null); ok {
		return x.Null
	}
	return false
}

func (m *Value) GetSingle() string {
	if x, ok := m.GetValue().(*Value_Single); ok {
		return x.Single
	}
	return ""
}

func (m *Value) GetRepeated() *Value_Repeated {
	if x, ok := m.GetValue().(*Value_Repeated_); ok {
		return x.Repeated
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Value) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Value_Null)(nil),
		(*Value_Single)(nil),
		(*Value_Repeated_)(nil),
	}
}

// Repeated values
type Value_Repeated struct {
	Values               []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Value_Repeated) Reset()         { *m = Value_Repeated{} }
func (m *Value_Repeated) String() string { return proto.CompactTextString(m) }
func (*Value_Repeated) ProtoMessage()    {}
func (*Value_Repeated) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c929259feb9628e, []int{0, 0}
}

func (m *Value_Repeated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value_Repeated.Unmarshal(m, b)
}
func (m *Value_Repeated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value_Repeated.Marshal(b, m, deterministic)
}
func (m *Value_Repeated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value_Repeated.Merge(m, src)
}
func (m *Value_Repeated) XXX_Size() int {
	return xxx_messageInfo_Value_Repeated.Size(m)
}
func (m *Value_Repeated) XXX_DiscardUnknown() {
	xxx_messageInfo_Value_Repeated.DiscardUnknown(m)
}

var xxx_messageInfo_Value_Repeated proto.InternalMessageInfo

func (m *Value_Repeated) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

func init() {
	proto.RegisterType((*Value)(nil), "sajari.engine.Value")
	proto.RegisterType((*Value_Repeated)(nil), "sajari.engine.Value.Repeated")
}

func init() { proto.RegisterFile("sajari/engine/value.proto", fileDescriptor_0c929259feb9628e) }

var fileDescriptor_0c929259feb9628e = []byte{
	// 199 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2c, 0x4e, 0xcc, 0x4a,
	0x2c, 0xca, 0xd4, 0x4f, 0xcd, 0x4b, 0xcf, 0xcc, 0x4b, 0xd5, 0x2f, 0x4b, 0xcc, 0x29, 0x4d, 0xd5,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x85, 0x48, 0xe9, 0x41, 0xa4, 0x94, 0x16, 0x32, 0x72,
	0xb1, 0x86, 0x81, 0xa4, 0x85, 0x44, 0xb8, 0x58, 0xf2, 0x4a, 0x73, 0x72, 0x24, 0x18, 0x15, 0x18,
	0x35, 0x38, 0x3c, 0x18, 0x82, 0xc0, 0x3c, 0x21, 0x09, 0x2e, 0xb6, 0xe2, 0xcc, 0xbc, 0xf4, 0x9c,
	0x54, 0x09, 0x26, 0x05, 0x46, 0x0d, 0x4e, 0x0f, 0x86, 0x20, 0x28, 0x5f, 0xc8, 0x9a, 0x8b, 0xa3,
	0x28, 0xb5, 0x20, 0x35, 0xb1, 0x24, 0x35, 0x45, 0x82, 0x59, 0x81, 0x51, 0x83, 0xdb, 0x48, 0x56,
	0x0f, 0xc5, 0x6c, 0x3d, 0xb0, 0xb9, 0x7a, 0x41, 0x50, 0x45, 0x1e, 0x0c, 0x41, 0x70, 0x0d, 0x52,
	0x4a, 0x5c, 0x1c, 0x30, 0x71, 0x21, 0x31, 0x2e, 0x36, 0xb0, 0x03, 0x8b, 0x25, 0x18, 0x15, 0x98,
	0x35, 0x38, 0x83, 0xa0, 0x3c, 0x27, 0x76, 0x2e, 0x56, 0x30, 0xcb, 0x49, 0x3b, 0x4a, 0x33, 0x39,
	0x3f, 0x25, 0x15, 0x66, 0x7a, 0x72, 0x7e, 0xae, 0x3e, 0xd8, 0x2f, 0xe9, 0xa9, 0x79, 0xba, 0xe9,
	0xf9, 0xfa, 0x28, 0x7e, 0x4d, 0x62, 0x03, 0x4b, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x7d,
	0xac, 0xf5, 0xfa, 0x03, 0x01, 0x00, 0x00,
}
