// Code generated by protoc-gen-go.
// source: sajari/api/pipeline/v1/pipeline.proto
// DO NOT EDIT!

/*
Package sajari_api_pipeline_v1 is a generated protocol buffer package.

It is generated from these files:
	sajari/api/pipeline/v1/pipeline.proto

It has these top-level messages:
	Pipeline
	SearchRequest
	SearchResponse
*/
package sajari_api_pipeline_v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import sajari_api_query_v1 "github.com/sajari/protogen-go/sajari/api/query/v1"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Pipeline is an identifier used to specify a pipeline.
type Pipeline struct {
	// Types that are valid to be assigned to Pipeline:
	//	*Pipeline_Name
	Pipeline isPipeline_Pipeline `protobuf_oneof:"pipeline"`
}

func (m *Pipeline) Reset()                    { *m = Pipeline{} }
func (m *Pipeline) String() string            { return proto.CompactTextString(m) }
func (*Pipeline) ProtoMessage()               {}
func (*Pipeline) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isPipeline_Pipeline interface {
	isPipeline_Pipeline()
}

type Pipeline_Name struct {
	Name string `protobuf:"bytes,1,opt,name=name,oneof"`
}

func (*Pipeline_Name) isPipeline_Pipeline() {}

func (m *Pipeline) GetPipeline() isPipeline_Pipeline {
	if m != nil {
		return m.Pipeline
	}
	return nil
}

func (m *Pipeline) GetName() string {
	if x, ok := m.GetPipeline().(*Pipeline_Name); ok {
		return x.Name
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Pipeline) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Pipeline_OneofMarshaler, _Pipeline_OneofUnmarshaler, _Pipeline_OneofSizer, []interface{}{
		(*Pipeline_Name)(nil),
	}
}

func _Pipeline_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Pipeline)
	// pipeline
	switch x := m.Pipeline.(type) {
	case *Pipeline_Name:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Name)
	case nil:
	default:
		return fmt.Errorf("Pipeline.Pipeline has unexpected type %T", x)
	}
	return nil
}

func _Pipeline_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Pipeline)
	switch tag {
	case 1: // pipeline.name
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Pipeline = &Pipeline_Name{x}
		return true, err
	default:
		return false, nil
	}
}

func _Pipeline_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Pipeline)
	// pipeline
	switch x := m.Pipeline.(type) {
	case *Pipeline_Name:
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Name)))
		n += len(x.Name)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// SearchRequest is a request to perform a search using a pipeline.
type SearchRequest struct {
	// Pipeline to run.
	Pipeline *Pipeline `protobuf:"bytes,1,opt,name=pipeline" json:"pipeline,omitempty"`
	// Values is a mapping of key -> value which should be substituted
	// into the algorithm inputs.
	Values map[string]string `protobuf:"bytes,2,rep,name=values" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Tracking is the tracking configuration.
	Tracking *sajari_api_query_v1.SearchRequest_Tracking `protobuf:"bytes,3,opt,name=tracking" json:"tracking,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SearchRequest) GetPipeline() *Pipeline {
	if m != nil {
		return m.Pipeline
	}
	return nil
}

func (m *SearchRequest) GetValues() map[string]string {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *SearchRequest) GetTracking() *sajari_api_query_v1.SearchRequest_Tracking {
	if m != nil {
		return m.Tracking
	}
	return nil
}

// SearchResponse is a response to a Search call.
type SearchResponse struct {
	// Input values with updates/modifications by querying system.
	Values map[string]string `protobuf:"bytes,1,rep,name=values" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// SearchResponse is the response returned by the raw API.
	SearchResponse *sajari_api_query_v1.SearchResponse `protobuf:"bytes,2,opt,name=search_response,json=searchResponse" json:"search_response,omitempty"`
}

func (m *SearchResponse) Reset()                    { *m = SearchResponse{} }
func (m *SearchResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()               {}
func (*SearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SearchResponse) GetValues() map[string]string {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *SearchResponse) GetSearchResponse() *sajari_api_query_v1.SearchResponse {
	if m != nil {
		return m.SearchResponse
	}
	return nil
}

func init() {
	proto.RegisterType((*Pipeline)(nil), "sajari.api.pipeline.v1.Pipeline")
	proto.RegisterType((*SearchRequest)(nil), "sajari.api.pipeline.v1.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "sajari.api.pipeline.v1.SearchResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Query service

type QueryClient interface {
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
}

type queryClient struct {
	cc *grpc.ClientConn
}

func NewQueryClient(cc *grpc.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := grpc.Invoke(ctx, "/sajari.api.pipeline.v1.Query/Search", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Query service

type QueryServer interface {
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
}

func RegisterQueryServer(s *grpc.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sajari.api.pipeline.v1.Query/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sajari.api.pipeline.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _Query_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sajari/api/pipeline/v1/pipeline.proto",
}

func init() { proto.RegisterFile("sajari/api/pipeline/v1/pipeline.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 332 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x92, 0xdf, 0x4a, 0xc3, 0x30,
	0x18, 0xc5, 0x6d, 0xe7, 0xc6, 0xfc, 0x8a, 0x53, 0xc2, 0x90, 0xb2, 0x1b, 0xc7, 0x64, 0x32, 0x50,
	0x32, 0x5a, 0x6f, 0x54, 0xbc, 0x12, 0xc4, 0x3f, 0x78, 0xa1, 0x51, 0xf4, 0x52, 0xe3, 0x08, 0x1a,
	0x37, 0xdb, 0x2c, 0x69, 0x0b, 0x7d, 0x17, 0x5f, 0xcf, 0xf7, 0x90, 0x26, 0x6d, 0xed, 0x70, 0xea,
	0xc0, 0xbb, 0x7c, 0xcd, 0xf9, 0x9d, 0xf3, 0x9d, 0xb6, 0xd0, 0x57, 0xf4, 0x95, 0x4a, 0x3e, 0xa4,
	0x82, 0x0f, 0x05, 0x17, 0x6c, 0xc2, 0x03, 0x36, 0x4c, 0xbc, 0xf2, 0x8c, 0x85, 0x0c, 0xa3, 0x10,
	0x6d, 0x18, 0x19, 0xa6, 0x82, 0xe3, 0xf2, 0x2a, 0xf1, 0x3a, 0x9b, 0x15, 0x7c, 0x1a, 0x33, 0x99,
	0x66, 0xac, 0x3e, 0x18, 0xb0, 0xb7, 0x0b, 0xcd, 0xab, 0x5c, 0x8f, 0xda, 0xb0, 0x1c, 0xd0, 0x37,
	0xe6, 0x5a, 0x5d, 0x6b, 0xb0, 0x72, 0xb6, 0x44, 0xf4, 0x74, 0x0c, 0xd0, 0x2c, 0x1c, 0x7b, 0xef,
	0x36, 0xac, 0xde, 0x30, 0x2a, 0x47, 0x2f, 0x84, 0x4d, 0x63, 0xa6, 0x22, 0x74, 0xf4, 0x75, 0xab,
	0x39, 0xc7, 0xef, 0xe2, 0xf9, 0xbb, 0xe0, 0x22, 0x87, 0x94, 0x04, 0x3a, 0x87, 0x46, 0x42, 0x27,
	0x31, 0x53, 0xae, 0xdd, 0xad, 0x0d, 0x1c, 0xdf, 0xfb, 0x89, 0x9d, 0x09, 0xc5, 0x77, 0x9a, 0x39,
	0x09, 0x22, 0x99, 0x92, 0xdc, 0x00, 0x9d, 0x42, 0x33, 0x92, 0x74, 0x34, 0xe6, 0xc1, 0xb3, 0x5b,
	0xd3, 0x8b, 0xec, 0x54, 0xcd, 0x4c, 0xe7, 0x6f, 0x4e, 0xb7, 0x39, 0x42, 0x4a, 0xb8, 0x73, 0x00,
	0x4e, 0xc5, 0x1f, 0xad, 0x43, 0x6d, 0xcc, 0x52, 0xf3, 0x4e, 0x48, 0x76, 0x44, 0x6d, 0xa8, 0xeb,
	0x4c, 0xd7, 0xd6, 0xcf, 0xcc, 0x70, 0x68, 0xef, 0x5b, 0xbd, 0x0f, 0x0b, 0x5a, 0x85, 0xbf, 0x12,
	0x61, 0xa0, 0x18, 0xba, 0x28, 0x1b, 0x5a, 0xba, 0xa1, 0xff, 0x57, 0x43, 0xc3, 0xcd, 0xad, 0x78,
	0x09, 0x6b, 0x4a, 0xab, 0x1e, 0x64, 0x2e, 0xd3, 0x2b, 0x38, 0xfe, 0xd6, 0xaf, 0x4d, 0x8d, 0x94,
	0xb4, 0xd4, 0xcc, 0xfc, 0x8f, 0x9e, 0xfe, 0x23, 0xd4, 0xaf, 0xb3, 0x14, 0x74, 0x0f, 0x0d, 0x93,
	0x82, 0xfa, 0x0b, 0x7d, 0xb9, 0xce, 0xf6, 0x62, 0xf5, 0x9f, 0x1a, 0xfa, 0xef, 0xdc, 0xfb, 0x0c,
	0x00, 0x00, 0xff, 0xff, 0xb8, 0x67, 0x1e, 0x4e, 0xff, 0x02, 0x00, 0x00,
}
