// Code generated by protoc-gen-go.
// source: sajari/rpc/empty.proto
// DO NOT EDIT!

/*
Package sajari_rpc is a generated protocol buffer package.

It is generated from these files:
	sajari/rpc/empty.proto
	sajari/rpc/status.proto

It has these top-level messages:
	Empty
	Status
*/
package sajari_rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Empty is a message used when there is no value returned
// from a call.
type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func init() {
	proto.RegisterType((*Empty)(nil), "sajari.rpc.Empty")
}

func init() { proto.RegisterFile("sajari/rpc/empty.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 68 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x2b, 0x4e, 0xcc, 0x4a,
	0x2c, 0xca, 0xd4, 0x2f, 0x2a, 0x48, 0xd6, 0x4f, 0xcd, 0x2d, 0x28, 0xa9, 0xd4, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0xe2, 0x82, 0x88, 0xeb, 0x15, 0x15, 0x24, 0x2b, 0xb1, 0x73, 0xb1, 0xba, 0x82,
	0xa4, 0x92, 0xd8, 0xc0, 0x72, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd4, 0x42, 0x97, 0xd7,
	0x35, 0x00, 0x00, 0x00,
}
