// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sajari/pipeline/v2/documentation.proto

package pipelinepb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetPipelineDocumentationRequest struct {
	Type                 Type        `protobuf:"varint,1,opt,name=type,proto3,enum=sajari.pipeline.v2.Type" json:"type,omitempty"`
	Pipeline             *Identifier `protobuf:"bytes,2,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetPipelineDocumentationRequest) Reset()         { *m = GetPipelineDocumentationRequest{} }
func (m *GetPipelineDocumentationRequest) String() string { return proto.CompactTextString(m) }
func (*GetPipelineDocumentationRequest) ProtoMessage()    {}
func (*GetPipelineDocumentationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fca4025792f792a, []int{0}
}

func (m *GetPipelineDocumentationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPipelineDocumentationRequest.Unmarshal(m, b)
}
func (m *GetPipelineDocumentationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPipelineDocumentationRequest.Marshal(b, m, deterministic)
}
func (m *GetPipelineDocumentationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPipelineDocumentationRequest.Merge(m, src)
}
func (m *GetPipelineDocumentationRequest) XXX_Size() int {
	return xxx_messageInfo_GetPipelineDocumentationRequest.Size(m)
}
func (m *GetPipelineDocumentationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPipelineDocumentationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPipelineDocumentationRequest proto.InternalMessageInfo

func (m *GetPipelineDocumentationRequest) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_TYPE_UNSPECIFIED
}

func (m *GetPipelineDocumentationRequest) GetPipeline() *Identifier {
	if m != nil {
		return m.Pipeline
	}
	return nil
}

// Usage is a message containing usage information for a query pipeline.
type GetPipelineDocumentationResponse struct {
	Type Type `protobuf:"varint,1,opt,name=type,proto3,enum=sajari.pipeline.v2.Type" json:"type,omitempty"`
	// Pipeline is the pipeline that this describes.
	Pipeline *Identifier `protobuf:"bytes,2,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	// Steps is the list of steps that will be run for the pipeline.
	PreSteps []*Step `protobuf:"bytes,3,rep,name=pre_steps,json=preSteps,proto3" json:"pre_steps,omitempty"`
	// Steps is the list of steps that will be run after the record
	// has been applied to the engine.
	PostSteps []*Step `protobuf:"bytes,4,rep,name=post_steps,json=postSteps,proto3" json:"post_steps,omitempty"`
	// List of input parameters used in the pipeline.
	Inputs []*Parameter `protobuf:"bytes,5,rep,name=inputs,proto3" json:"inputs,omitempty"`
	// List of output parameters returned by the pipeline.
	Outputs              []*Parameter `protobuf:"bytes,6,rep,name=outputs,proto3" json:"outputs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetPipelineDocumentationResponse) Reset()         { *m = GetPipelineDocumentationResponse{} }
func (m *GetPipelineDocumentationResponse) String() string { return proto.CompactTextString(m) }
func (*GetPipelineDocumentationResponse) ProtoMessage()    {}
func (*GetPipelineDocumentationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fca4025792f792a, []int{1}
}

func (m *GetPipelineDocumentationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPipelineDocumentationResponse.Unmarshal(m, b)
}
func (m *GetPipelineDocumentationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPipelineDocumentationResponse.Marshal(b, m, deterministic)
}
func (m *GetPipelineDocumentationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPipelineDocumentationResponse.Merge(m, src)
}
func (m *GetPipelineDocumentationResponse) XXX_Size() int {
	return xxx_messageInfo_GetPipelineDocumentationResponse.Size(m)
}
func (m *GetPipelineDocumentationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPipelineDocumentationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPipelineDocumentationResponse proto.InternalMessageInfo

func (m *GetPipelineDocumentationResponse) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_TYPE_UNSPECIFIED
}

func (m *GetPipelineDocumentationResponse) GetPipeline() *Identifier {
	if m != nil {
		return m.Pipeline
	}
	return nil
}

func (m *GetPipelineDocumentationResponse) GetPreSteps() []*Step {
	if m != nil {
		return m.PreSteps
	}
	return nil
}

func (m *GetPipelineDocumentationResponse) GetPostSteps() []*Step {
	if m != nil {
		return m.PostSteps
	}
	return nil
}

func (m *GetPipelineDocumentationResponse) GetInputs() []*Parameter {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *GetPipelineDocumentationResponse) GetOutputs() []*Parameter {
	if m != nil {
		return m.Outputs
	}
	return nil
}

// Parameter defines a parameter used in pipelines to pass
// user-defined values.
type Parameter struct {
	// Identifier for this parameter.
	Identifier string `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	// Name of the pipeline parameter.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Type of the pipeline parameter.
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	// Description for the paramter.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Default value of the parameter.
	DefaultValue         string   `protobuf:"bytes,5,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Parameter) Reset()         { *m = Parameter{} }
func (m *Parameter) String() string { return proto.CompactTextString(m) }
func (*Parameter) ProtoMessage()    {}
func (*Parameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fca4025792f792a, []int{2}
}

func (m *Parameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Parameter.Unmarshal(m, b)
}
func (m *Parameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Parameter.Marshal(b, m, deterministic)
}
func (m *Parameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Parameter.Merge(m, src)
}
func (m *Parameter) XXX_Size() int {
	return xxx_messageInfo_Parameter.Size(m)
}
func (m *Parameter) XXX_DiscardUnknown() {
	xxx_messageInfo_Parameter.DiscardUnknown(m)
}

var xxx_messageInfo_Parameter proto.InternalMessageInfo

func (m *Parameter) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *Parameter) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Parameter) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Parameter) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Parameter) GetDefaultValue() string {
	if m != nil {
		return m.DefaultValue
	}
	return ""
}

// Constant defines a constant used in a pipeline step, set by
// the pipeline creator but cannot be changed by the caller.
type Constant struct {
	// Identifier for the constant.
	Identifier string `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	// Name of the constant.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Type of the constant.
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	// Description informtion for the constant.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Value of the constant.
	Value                string   `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Constant) Reset()         { *m = Constant{} }
func (m *Constant) String() string { return proto.CompactTextString(m) }
func (*Constant) ProtoMessage()    {}
func (*Constant) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fca4025792f792a, []int{3}
}

func (m *Constant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Constant.Unmarshal(m, b)
}
func (m *Constant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Constant.Marshal(b, m, deterministic)
}
func (m *Constant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Constant.Merge(m, src)
}
func (m *Constant) XXX_Size() int {
	return xxx_messageInfo_Constant.Size(m)
}
func (m *Constant) XXX_DiscardUnknown() {
	xxx_messageInfo_Constant.DiscardUnknown(m)
}

var xxx_messageInfo_Constant proto.InternalMessageInfo

func (m *Constant) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *Constant) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Constant) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Constant) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Constant) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// Step represents a single unit of work performed by the pipeline.
type Step struct {
	// Type of pipeline this step applies to.
	Type Type `protobuf:"varint,1,opt,name=type,proto3,enum=sajari.pipeline.v2.Type" json:"type,omitempty"`
	// Type of step.
	StepType StepType `protobuf:"varint,2,opt,name=step_type,json=stepType,proto3,enum=sajari.pipeline.v2.StepType" json:"step_type,omitempty"`
	// Identifier
	Identifier string `protobuf:"bytes,3,opt,name=identifier,proto3" json:"identifier,omitempty"`
	// Name of the action.
	Title string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	// Description of the action.
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	// List of input parameters used by the step.
	Inputs []*Parameter `protobuf:"bytes,6,rep,name=inputs,proto3" json:"inputs,omitempty"`
	// List of output parameters returned by the step.
	Outputs []*Parameter `protobuf:"bytes,7,rep,name=outputs,proto3" json:"outputs,omitempty"`
	// List of constants used by the step.
	Constants            []*Constant `protobuf:"bytes,8,rep,name=constants,proto3" json:"constants,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Step) Reset()         { *m = Step{} }
func (m *Step) String() string { return proto.CompactTextString(m) }
func (*Step) ProtoMessage()    {}
func (*Step) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fca4025792f792a, []int{4}
}

func (m *Step) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Step.Unmarshal(m, b)
}
func (m *Step) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Step.Marshal(b, m, deterministic)
}
func (m *Step) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Step.Merge(m, src)
}
func (m *Step) XXX_Size() int {
	return xxx_messageInfo_Step.Size(m)
}
func (m *Step) XXX_DiscardUnknown() {
	xxx_messageInfo_Step.DiscardUnknown(m)
}

var xxx_messageInfo_Step proto.InternalMessageInfo

func (m *Step) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_TYPE_UNSPECIFIED
}

func (m *Step) GetStepType() StepType {
	if m != nil {
		return m.StepType
	}
	return StepType_STEP_TYPE_UNSPECIFIED
}

func (m *Step) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *Step) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Step) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Step) GetInputs() []*Parameter {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *Step) GetOutputs() []*Parameter {
	if m != nil {
		return m.Outputs
	}
	return nil
}

func (m *Step) GetConstants() []*Constant {
	if m != nil {
		return m.Constants
	}
	return nil
}

// ListStepsRequest is used to request a listing of steps.
type ListStepsRequest struct {
	// Type of pipeline steps to list (query/record).
	Type Type `protobuf:"varint,1,opt,name=type,proto3,enum=sajari.pipeline.v2.Type" json:"type,omitempty"`
	// Step types to list (pre/post).
	StepType StepType `protobuf:"varint,2,opt,name=step_type,json=stepType,proto3,enum=sajari.pipeline.v2.StepType" json:"step_type,omitempty"`
	// The maximum number of steps to return.
	PageSize int32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// The `next_page_token` value returned from a previous List request, if any.
	PageToken            string   `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListStepsRequest) Reset()         { *m = ListStepsRequest{} }
func (m *ListStepsRequest) String() string { return proto.CompactTextString(m) }
func (*ListStepsRequest) ProtoMessage()    {}
func (*ListStepsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fca4025792f792a, []int{5}
}

func (m *ListStepsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListStepsRequest.Unmarshal(m, b)
}
func (m *ListStepsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListStepsRequest.Marshal(b, m, deterministic)
}
func (m *ListStepsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListStepsRequest.Merge(m, src)
}
func (m *ListStepsRequest) XXX_Size() int {
	return xxx_messageInfo_ListStepsRequest.Size(m)
}
func (m *ListStepsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListStepsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListStepsRequest proto.InternalMessageInfo

func (m *ListStepsRequest) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_TYPE_UNSPECIFIED
}

func (m *ListStepsRequest) GetStepType() StepType {
	if m != nil {
		return m.StepType
	}
	return StepType_STEP_TYPE_UNSPECIFIED
}

func (m *ListStepsRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListStepsRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

// ListStepsResponse contains a list of steps.
type ListStepsResponse struct {
	// List of steps.
	Steps []*ListStepsResponse_Step `protobuf:"bytes,1,rep,name=steps,proto3" json:"steps,omitempty"`
	// The next page token.
	NextPageToken        string   `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListStepsResponse) Reset()         { *m = ListStepsResponse{} }
func (m *ListStepsResponse) String() string { return proto.CompactTextString(m) }
func (*ListStepsResponse) ProtoMessage()    {}
func (*ListStepsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fca4025792f792a, []int{6}
}

func (m *ListStepsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListStepsResponse.Unmarshal(m, b)
}
func (m *ListStepsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListStepsResponse.Marshal(b, m, deterministic)
}
func (m *ListStepsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListStepsResponse.Merge(m, src)
}
func (m *ListStepsResponse) XXX_Size() int {
	return xxx_messageInfo_ListStepsResponse.Size(m)
}
func (m *ListStepsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListStepsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListStepsResponse proto.InternalMessageInfo

func (m *ListStepsResponse) GetSteps() []*ListStepsResponse_Step {
	if m != nil {
		return m.Steps
	}
	return nil
}

func (m *ListStepsResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

// Step
type ListStepsResponse_Step struct {
	// Type of pipeline this step refers to.
	Type Type `protobuf:"varint,1,opt,name=type,proto3,enum=sajari.pipeline.v2.Type" json:"type,omitempty"`
	// Type of step (pre/post).
	StepType StepType `protobuf:"varint,2,opt,name=step_type,json=stepType,proto3,enum=sajari.pipeline.v2.StepType" json:"step_type,omitempty"`
	// Identifer for step.
	Identifier string `protobuf:"bytes,3,opt,name=identifier,proto3" json:"identifier,omitempty"`
	// Title of step.
	Title string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	// Description of step.
	Description          string   `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListStepsResponse_Step) Reset()         { *m = ListStepsResponse_Step{} }
func (m *ListStepsResponse_Step) String() string { return proto.CompactTextString(m) }
func (*ListStepsResponse_Step) ProtoMessage()    {}
func (*ListStepsResponse_Step) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fca4025792f792a, []int{6, 0}
}

func (m *ListStepsResponse_Step) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListStepsResponse_Step.Unmarshal(m, b)
}
func (m *ListStepsResponse_Step) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListStepsResponse_Step.Marshal(b, m, deterministic)
}
func (m *ListStepsResponse_Step) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListStepsResponse_Step.Merge(m, src)
}
func (m *ListStepsResponse_Step) XXX_Size() int {
	return xxx_messageInfo_ListStepsResponse_Step.Size(m)
}
func (m *ListStepsResponse_Step) XXX_DiscardUnknown() {
	xxx_messageInfo_ListStepsResponse_Step.DiscardUnknown(m)
}

var xxx_messageInfo_ListStepsResponse_Step proto.InternalMessageInfo

func (m *ListStepsResponse_Step) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_TYPE_UNSPECIFIED
}

func (m *ListStepsResponse_Step) GetStepType() StepType {
	if m != nil {
		return m.StepType
	}
	return StepType_STEP_TYPE_UNSPECIFIED
}

func (m *ListStepsResponse_Step) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *ListStepsResponse_Step) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ListStepsResponse_Step) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

// GetStepDocumentationRequest
type GetStepDocumentationRequest struct {
	// Type of pipeline to fetch step for.
	Type Type `protobuf:"varint,1,opt,name=type,proto3,enum=sajari.pipeline.v2.Type" json:"type,omitempty"`
	// Type of step to fetch.
	StepType StepType `protobuf:"varint,2,opt,name=step_type,json=stepType,proto3,enum=sajari.pipeline.v2.StepType" json:"step_type,omitempty"`
	// Identifier for step.
	Identifier           string   `protobuf:"bytes,3,opt,name=identifier,proto3" json:"identifier,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStepDocumentationRequest) Reset()         { *m = GetStepDocumentationRequest{} }
func (m *GetStepDocumentationRequest) String() string { return proto.CompactTextString(m) }
func (*GetStepDocumentationRequest) ProtoMessage()    {}
func (*GetStepDocumentationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fca4025792f792a, []int{7}
}

func (m *GetStepDocumentationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStepDocumentationRequest.Unmarshal(m, b)
}
func (m *GetStepDocumentationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStepDocumentationRequest.Marshal(b, m, deterministic)
}
func (m *GetStepDocumentationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStepDocumentationRequest.Merge(m, src)
}
func (m *GetStepDocumentationRequest) XXX_Size() int {
	return xxx_messageInfo_GetStepDocumentationRequest.Size(m)
}
func (m *GetStepDocumentationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStepDocumentationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStepDocumentationRequest proto.InternalMessageInfo

func (m *GetStepDocumentationRequest) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_TYPE_UNSPECIFIED
}

func (m *GetStepDocumentationRequest) GetStepType() StepType {
	if m != nil {
		return m.StepType
	}
	return StepType_STEP_TYPE_UNSPECIFIED
}

func (m *GetStepDocumentationRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

// GetStepDocumentationResponse
type GetStepDocumentationResponse struct {
	// Type of the pipeline.
	Type Type `protobuf:"varint,1,opt,name=type,proto3,enum=sajari.pipeline.v2.Type" json:"type,omitempty"`
	// Type of the step.
	StepType StepType `protobuf:"varint,2,opt,name=step_type,json=stepType,proto3,enum=sajari.pipeline.v2.StepType" json:"step_type,omitempty"`
	// Step information.
	Step                 *Step    `protobuf:"bytes,3,opt,name=step,proto3" json:"step,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStepDocumentationResponse) Reset()         { *m = GetStepDocumentationResponse{} }
func (m *GetStepDocumentationResponse) String() string { return proto.CompactTextString(m) }
func (*GetStepDocumentationResponse) ProtoMessage()    {}
func (*GetStepDocumentationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fca4025792f792a, []int{8}
}

func (m *GetStepDocumentationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStepDocumentationResponse.Unmarshal(m, b)
}
func (m *GetStepDocumentationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStepDocumentationResponse.Marshal(b, m, deterministic)
}
func (m *GetStepDocumentationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStepDocumentationResponse.Merge(m, src)
}
func (m *GetStepDocumentationResponse) XXX_Size() int {
	return xxx_messageInfo_GetStepDocumentationResponse.Size(m)
}
func (m *GetStepDocumentationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStepDocumentationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStepDocumentationResponse proto.InternalMessageInfo

func (m *GetStepDocumentationResponse) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_TYPE_UNSPECIFIED
}

func (m *GetStepDocumentationResponse) GetStepType() StepType {
	if m != nil {
		return m.StepType
	}
	return StepType_STEP_TYPE_UNSPECIFIED
}

func (m *GetStepDocumentationResponse) GetStep() *Step {
	if m != nil {
		return m.Step
	}
	return nil
}

func init() {
	proto.RegisterType((*GetPipelineDocumentationRequest)(nil), "sajari.pipeline.v2.GetPipelineDocumentationRequest")
	proto.RegisterType((*GetPipelineDocumentationResponse)(nil), "sajari.pipeline.v2.GetPipelineDocumentationResponse")
	proto.RegisterType((*Parameter)(nil), "sajari.pipeline.v2.Parameter")
	proto.RegisterType((*Constant)(nil), "sajari.pipeline.v2.Constant")
	proto.RegisterType((*Step)(nil), "sajari.pipeline.v2.Step")
	proto.RegisterType((*ListStepsRequest)(nil), "sajari.pipeline.v2.ListStepsRequest")
	proto.RegisterType((*ListStepsResponse)(nil), "sajari.pipeline.v2.ListStepsResponse")
	proto.RegisterType((*ListStepsResponse_Step)(nil), "sajari.pipeline.v2.ListStepsResponse.Step")
	proto.RegisterType((*GetStepDocumentationRequest)(nil), "sajari.pipeline.v2.GetStepDocumentationRequest")
	proto.RegisterType((*GetStepDocumentationResponse)(nil), "sajari.pipeline.v2.GetStepDocumentationResponse")
}

func init() {
	proto.RegisterFile("sajari/pipeline/v2/documentation.proto", fileDescriptor_8fca4025792f792a)
}

var fileDescriptor_8fca4025792f792a = []byte{
	// 680 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x56, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0xd5, 0x24, 0x71, 0x1a, 0xdf, 0x7e, 0xfd, 0x80, 0x51, 0x17, 0x56, 0xfa, 0x43, 0x30, 0x50,
	0x55, 0xa8, 0xc4, 0x28, 0xa5, 0xaa, 0xda, 0x6e, 0x10, 0x20, 0x55, 0x48, 0x2c, 0x2a, 0xb7, 0x42,
	0x88, 0x4d, 0xe4, 0x26, 0xb7, 0xd5, 0x40, 0xe2, 0x19, 0x3c, 0xe3, 0x8a, 0x76, 0xcf, 0x06, 0xde,
	0x80, 0x07, 0xe0, 0x0d, 0x10, 0x8f, 0xd0, 0x97, 0xe9, 0x8e, 0x17, 0x40, 0x9e, 0xb1, 0x53, 0xd3,
	0x38, 0xb4, 0x4d, 0xa1, 0x0b, 0x76, 0xe3, 0x3b, 0xe7, 0x78, 0xce, 0xbd, 0xf7, 0xcc, 0x0f, 0x2c,
	0xc8, 0xe0, 0x6d, 0x10, 0x31, 0x4f, 0x30, 0x81, 0x3d, 0x16, 0xa2, 0x77, 0xd0, 0xf2, 0xba, 0xbc,
	0x13, 0xf7, 0x31, 0x54, 0x81, 0x62, 0x3c, 0x6c, 0x8a, 0x88, 0x2b, 0x4e, 0xa9, 0xc1, 0x35, 0x33,
	0x5c, 0xf3, 0xa0, 0x55, 0xbf, 0x53, 0xc0, 0x1d, 0xcc, 0x6b, 0x9a, 0xfb, 0x99, 0xc0, 0xed, 0x4d,
	0x54, 0x5b, 0x69, 0xf4, 0x79, 0xfe, 0xcf, 0x3e, 0xbe, 0x8f, 0x51, 0x2a, 0xba, 0x04, 0x15, 0x75,
	0x28, 0xd0, 0x21, 0x0d, 0xb2, 0xf8, 0x7f, 0xcb, 0x69, 0x0e, 0xaf, 0xd4, 0xdc, 0x39, 0x14, 0xe8,
	0x6b, 0x14, 0x5d, 0x87, 0x5a, 0x36, 0xe3, 0x94, 0x1a, 0x64, 0x71, 0xb2, 0x35, 0x5f, 0xc4, 0x78,
	0xd1, 0xc5, 0x50, 0xb1, 0x3d, 0x86, 0x91, 0x3f, 0xc0, 0xbb, 0x27, 0x25, 0x68, 0x8c, 0x56, 0x23,
	0x05, 0x0f, 0x25, 0x5e, 0x9f, 0x1c, 0xba, 0x02, 0xb6, 0x88, 0xb0, 0x2d, 0x15, 0x0a, 0xe9, 0x94,
	0x1b, 0xe5, 0xc5, 0xc9, 0xe2, 0xe5, 0xb6, 0x15, 0x0a, 0xbf, 0x26, 0x22, 0x4c, 0x06, 0x92, 0xae,
	0x02, 0x08, 0x2e, 0x55, 0xca, 0xab, 0x9c, 0xc3, 0xb3, 0x13, 0xac, 0x21, 0xae, 0x40, 0x95, 0x85,
	0x22, 0x56, 0xd2, 0xb1, 0x34, 0x69, 0xae, 0x88, 0xb4, 0x15, 0x44, 0x41, 0x1f, 0x15, 0x46, 0x7e,
	0x0a, 0xa6, 0xab, 0x30, 0xc1, 0x63, 0xa5, 0x79, 0xd5, 0x8b, 0xf0, 0x32, 0xb4, 0xfb, 0x85, 0x80,
	0x3d, 0x08, 0xd3, 0x79, 0x00, 0x36, 0xa8, 0x82, 0xae, 0xae, 0xed, 0xe7, 0x22, 0x94, 0x42, 0x25,
	0x0c, 0xfa, 0xa6, 0x8a, 0xb6, 0xaf, 0xc7, 0x49, 0x4c, 0xf7, 0xa2, 0x6c, 0x62, 0xba, 0xe2, 0x0d,
	0x98, 0xec, 0xa2, 0xec, 0x44, 0x4c, 0x24, 0x6d, 0x73, 0x2a, 0x7a, 0x2a, 0x1f, 0xa2, 0x77, 0x61,
	0xaa, 0x8b, 0x7b, 0x41, 0xdc, 0x53, 0xed, 0x83, 0xa0, 0x17, 0xa3, 0x63, 0x69, 0xcc, 0x7f, 0x69,
	0xf0, 0x55, 0x12, 0x73, 0x3f, 0x11, 0xa8, 0x3d, 0xe3, 0xa1, 0x54, 0x41, 0xa8, 0xae, 0x51, 0xdb,
	0x34, 0x58, 0x79, 0x4d, 0xe6, 0xc3, 0xfd, 0x51, 0x82, 0x4a, 0xd2, 0xa3, 0x4b, 0x9a, 0x6f, 0x0d,
	0xec, 0xc4, 0x04, 0x6d, 0x4d, 0x29, 0x69, 0xca, 0xec, 0x28, 0x23, 0x68, 0x5a, 0x4d, 0xa6, 0xa3,
	0x33, 0x19, 0x97, 0x87, 0x32, 0x9e, 0x06, 0x4b, 0x31, 0xd5, 0xc3, 0x34, 0x07, 0xf3, 0x71, 0x36,
	0x3f, 0x6b, 0x38, 0xbf, 0x53, 0x8f, 0x55, 0xc7, 0xf4, 0xd8, 0xc4, 0x65, 0x3c, 0x46, 0xd7, 0xc1,
	0xee, 0xa4, 0x5d, 0x94, 0x4e, 0x4d, 0x53, 0x0b, 0x4b, 0x90, 0xb5, 0xda, 0x3f, 0x85, 0xbb, 0xdf,
	0x09, 0xdc, 0x7c, 0xc9, 0xd2, 0xdd, 0x31, 0xde, 0x69, 0x74, 0x85, 0x0e, 0xcc, 0x80, 0x2d, 0x82,
	0x7d, 0x6c, 0x4b, 0x76, 0x64, 0x4c, 0x64, 0xf9, 0xb5, 0x24, 0xb0, 0xcd, 0x8e, 0x90, 0xce, 0x01,
	0xe8, 0x49, 0xc5, 0xdf, 0x61, 0xe6, 0x23, 0x0d, 0xdf, 0x49, 0x02, 0xee, 0x71, 0x09, 0x6e, 0xe5,
	0x94, 0xa7, 0x27, 0xd7, 0x13, 0xb0, 0xcc, 0x99, 0x40, 0x74, 0x1d, 0x1e, 0x14, 0x09, 0x19, 0x62,
	0x99, 0x53, 0xc2, 0x10, 0xe9, 0x02, 0xdc, 0x08, 0xf1, 0x83, 0x6a, 0xe7, 0xd6, 0x36, 0x96, 0x9f,
	0x4a, 0xc2, 0x5b, 0xd9, 0xfa, 0xf5, 0x63, 0xf2, 0x8f, 0xf8, 0xd5, 0xfd, 0x4a, 0x60, 0x66, 0x13,
	0x75, 0x49, 0xfe, 0xc0, 0xe5, 0xf4, 0xf7, 0x12, 0x74, 0xbf, 0x11, 0x98, 0x2d, 0x16, 0x3a, 0xd6,
	0xbd, 0x75, 0x05, 0xa5, 0x4b, 0x50, 0x49, 0xc6, 0x5a, 0xe3, 0xef, 0x6e, 0x1e, 0x8d, 0x6a, 0x9d,
	0x94, 0x60, 0xea, 0x17, 0xc1, 0xf4, 0x23, 0x01, 0x67, 0xd4, 0x2d, 0x4c, 0x97, 0x8b, 0x7e, 0x77,
	0xce, 0x0b, 0xa2, 0xfe, 0xf8, 0x72, 0xa4, 0xb4, 0x60, 0xaf, 0xc1, 0x1e, 0xec, 0x06, 0x7a, 0xef,
	0x9c, 0xcd, 0x62, 0x16, 0xba, 0x7f, 0xa1, 0x2d, 0x45, 0x0f, 0x61, 0xba, 0xa8, 0x55, 0xd4, 0x1b,
	0xa1, 0x73, 0x94, 0xfb, 0xea, 0x8f, 0x2e, 0x4e, 0x30, 0x4b, 0x3f, 0xdd, 0x78, 0xb3, 0xd6, 0xe1,
	0x5d, 0xcc, 0x78, 0x1d, 0xde, 0xf7, 0xf4, 0x4b, 0x6c, 0x1f, 0xc3, 0x87, 0xfb, 0xdc, 0x1b, 0x7e,
	0xb1, 0x6d, 0x64, 0x63, 0xb1, 0xbb, 0x5b, 0xd5, 0xd0, 0xe5, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xfc, 0x1b, 0xb3, 0x0a, 0x15, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DocumentationClient is the client API for Documentation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DocumentationClient interface {
	// GetPipelineDocumentation.
	GetPipelineDocumentation(ctx context.Context, in *GetPipelineDocumentationRequest, opts ...grpc.CallOption) (*GetPipelineDocumentationResponse, error)
	// List steps.
	ListSteps(ctx context.Context, in *ListStepsRequest, opts ...grpc.CallOption) (*ListStepsResponse, error)
	// Get step documentation.
	GetStepDocumentation(ctx context.Context, in *GetStepDocumentationRequest, opts ...grpc.CallOption) (*GetStepDocumentationResponse, error)
}

type documentationClient struct {
	cc *grpc.ClientConn
}

func NewDocumentationClient(cc *grpc.ClientConn) DocumentationClient {
	return &documentationClient{cc}
}

func (c *documentationClient) GetPipelineDocumentation(ctx context.Context, in *GetPipelineDocumentationRequest, opts ...grpc.CallOption) (*GetPipelineDocumentationResponse, error) {
	out := new(GetPipelineDocumentationResponse)
	err := c.cc.Invoke(ctx, "/sajari.pipeline.v2.Documentation/GetPipelineDocumentation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentationClient) ListSteps(ctx context.Context, in *ListStepsRequest, opts ...grpc.CallOption) (*ListStepsResponse, error) {
	out := new(ListStepsResponse)
	err := c.cc.Invoke(ctx, "/sajari.pipeline.v2.Documentation/ListSteps", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentationClient) GetStepDocumentation(ctx context.Context, in *GetStepDocumentationRequest, opts ...grpc.CallOption) (*GetStepDocumentationResponse, error) {
	out := new(GetStepDocumentationResponse)
	err := c.cc.Invoke(ctx, "/sajari.pipeline.v2.Documentation/GetStepDocumentation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DocumentationServer is the server API for Documentation service.
type DocumentationServer interface {
	// GetPipelineDocumentation.
	GetPipelineDocumentation(context.Context, *GetPipelineDocumentationRequest) (*GetPipelineDocumentationResponse, error)
	// List steps.
	ListSteps(context.Context, *ListStepsRequest) (*ListStepsResponse, error)
	// Get step documentation.
	GetStepDocumentation(context.Context, *GetStepDocumentationRequest) (*GetStepDocumentationResponse, error)
}

func RegisterDocumentationServer(s *grpc.Server, srv DocumentationServer) {
	s.RegisterService(&_Documentation_serviceDesc, srv)
}

func _Documentation_GetPipelineDocumentation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPipelineDocumentationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentationServer).GetPipelineDocumentation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sajari.pipeline.v2.Documentation/GetPipelineDocumentation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentationServer).GetPipelineDocumentation(ctx, req.(*GetPipelineDocumentationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Documentation_ListSteps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStepsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentationServer).ListSteps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sajari.pipeline.v2.Documentation/ListSteps",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentationServer).ListSteps(ctx, req.(*ListStepsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Documentation_GetStepDocumentation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStepDocumentationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentationServer).GetStepDocumentation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sajari.pipeline.v2.Documentation/GetStepDocumentation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentationServer).GetStepDocumentation(ctx, req.(*GetStepDocumentationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Documentation_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sajari.pipeline.v2.Documentation",
	HandlerType: (*DocumentationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPipelineDocumentation",
			Handler:    _Documentation_GetPipelineDocumentation_Handler,
		},
		{
			MethodName: "ListSteps",
			Handler:    _Documentation_ListSteps_Handler,
		},
		{
			MethodName: "GetStepDocumentation",
			Handler:    _Documentation_GetStepDocumentation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sajari/pipeline/v2/documentation.proto",
}
