// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sajari/pipeline/v2/documentation.proto

package pipelinepb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetPipelineDocumentationRequest struct {
	Pipeline             *TypeIdentifier `protobuf:"bytes,1,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetPipelineDocumentationRequest) Reset()         { *m = GetPipelineDocumentationRequest{} }
func (m *GetPipelineDocumentationRequest) String() string { return proto.CompactTextString(m) }
func (*GetPipelineDocumentationRequest) ProtoMessage()    {}
func (*GetPipelineDocumentationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fca4025792f792a, []int{0}
}

func (m *GetPipelineDocumentationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPipelineDocumentationRequest.Unmarshal(m, b)
}
func (m *GetPipelineDocumentationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPipelineDocumentationRequest.Marshal(b, m, deterministic)
}
func (m *GetPipelineDocumentationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPipelineDocumentationRequest.Merge(m, src)
}
func (m *GetPipelineDocumentationRequest) XXX_Size() int {
	return xxx_messageInfo_GetPipelineDocumentationRequest.Size(m)
}
func (m *GetPipelineDocumentationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPipelineDocumentationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPipelineDocumentationRequest proto.InternalMessageInfo

func (m *GetPipelineDocumentationRequest) GetPipeline() *TypeIdentifier {
	if m != nil {
		return m.Pipeline
	}
	return nil
}

// Usage is a message containing usage information for a query pipeline.
type GetPipelineDocumentationResponse struct {
	// Identifier for pipeline.
	Pipeline *TypeIdentifier `protobuf:"bytes,1,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	// Title.
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// Description.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Steps that will be run.
	Steps []*Steps `protobuf:"bytes,4,rep,name=steps,proto3" json:"steps,omitempty"`
	// List of input parameters used in the pipeline.
	Inputs []*Parameter `protobuf:"bytes,5,rep,name=inputs,proto3" json:"inputs,omitempty"`
	// List of output parameters returned by the pipeline.
	Outputs []*Parameter `protobuf:"bytes,6,rep,name=outputs,proto3" json:"outputs,omitempty"`
	// Time that the pipeline was created.
	CreateTime           *timestamp.Timestamp `protobuf:"bytes,7,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetPipelineDocumentationResponse) Reset()         { *m = GetPipelineDocumentationResponse{} }
func (m *GetPipelineDocumentationResponse) String() string { return proto.CompactTextString(m) }
func (*GetPipelineDocumentationResponse) ProtoMessage()    {}
func (*GetPipelineDocumentationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fca4025792f792a, []int{1}
}

func (m *GetPipelineDocumentationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPipelineDocumentationResponse.Unmarshal(m, b)
}
func (m *GetPipelineDocumentationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPipelineDocumentationResponse.Marshal(b, m, deterministic)
}
func (m *GetPipelineDocumentationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPipelineDocumentationResponse.Merge(m, src)
}
func (m *GetPipelineDocumentationResponse) XXX_Size() int {
	return xxx_messageInfo_GetPipelineDocumentationResponse.Size(m)
}
func (m *GetPipelineDocumentationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPipelineDocumentationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPipelineDocumentationResponse proto.InternalMessageInfo

func (m *GetPipelineDocumentationResponse) GetPipeline() *TypeIdentifier {
	if m != nil {
		return m.Pipeline
	}
	return nil
}

func (m *GetPipelineDocumentationResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *GetPipelineDocumentationResponse) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *GetPipelineDocumentationResponse) GetSteps() []*Steps {
	if m != nil {
		return m.Steps
	}
	return nil
}

func (m *GetPipelineDocumentationResponse) GetInputs() []*Parameter {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *GetPipelineDocumentationResponse) GetOutputs() []*Parameter {
	if m != nil {
		return m.Outputs
	}
	return nil
}

func (m *GetPipelineDocumentationResponse) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

type Steps struct {
	// Step type determines when the steps will be run.
	StepType StepType `protobuf:"varint,1,opt,name=step_type,json=stepType,proto3,enum=sajari.pipeline.v2.StepType" json:"step_type,omitempty"`
	// List of steps to run.
	Steps                []*Step  `protobuf:"bytes,2,rep,name=steps,proto3" json:"steps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Steps) Reset()         { *m = Steps{} }
func (m *Steps) String() string { return proto.CompactTextString(m) }
func (*Steps) ProtoMessage()    {}
func (*Steps) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fca4025792f792a, []int{2}
}

func (m *Steps) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Steps.Unmarshal(m, b)
}
func (m *Steps) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Steps.Marshal(b, m, deterministic)
}
func (m *Steps) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Steps.Merge(m, src)
}
func (m *Steps) XXX_Size() int {
	return xxx_messageInfo_Steps.Size(m)
}
func (m *Steps) XXX_DiscardUnknown() {
	xxx_messageInfo_Steps.DiscardUnknown(m)
}

var xxx_messageInfo_Steps proto.InternalMessageInfo

func (m *Steps) GetStepType() StepType {
	if m != nil {
		return m.StepType
	}
	return StepType_STEP_TYPE_UNSPECIFIED
}

func (m *Steps) GetSteps() []*Step {
	if m != nil {
		return m.Steps
	}
	return nil
}

// Parameter defines a parameter used in pipelines to pass user-defined values.
// It can be configured by the pipeline creater.
type Parameter struct {
	// Identifier for this parameter (from the step template).
	Identifier string `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	// Name of the parameter in this pipeline.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Type of the pipeline parameter (from the step template).
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	// Description for the paramter in this pipeline.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Default value of the parameter in this pipeline.
	DefaultValue         string   `protobuf:"bytes,5,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Parameter) Reset()         { *m = Parameter{} }
func (m *Parameter) String() string { return proto.CompactTextString(m) }
func (*Parameter) ProtoMessage()    {}
func (*Parameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fca4025792f792a, []int{3}
}

func (m *Parameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Parameter.Unmarshal(m, b)
}
func (m *Parameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Parameter.Marshal(b, m, deterministic)
}
func (m *Parameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Parameter.Merge(m, src)
}
func (m *Parameter) XXX_Size() int {
	return xxx_messageInfo_Parameter.Size(m)
}
func (m *Parameter) XXX_DiscardUnknown() {
	xxx_messageInfo_Parameter.DiscardUnknown(m)
}

var xxx_messageInfo_Parameter proto.InternalMessageInfo

func (m *Parameter) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *Parameter) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Parameter) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Parameter) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Parameter) GetDefaultValue() string {
	if m != nil {
		return m.DefaultValue
	}
	return ""
}

// Constant defines a constant used in a pipeline step. The value can be set by
// the pipeline creator but cannot be changed by the caller.
type Constant struct {
	// Name of the constant (from the step template).
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Type of the constant (from the step template).
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// Description informtion for the constant (from the step template).
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Value of the constant in this pipeline.
	Value                string   `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Constant) Reset()         { *m = Constant{} }
func (m *Constant) String() string { return proto.CompactTextString(m) }
func (*Constant) ProtoMessage()    {}
func (*Constant) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fca4025792f792a, []int{4}
}

func (m *Constant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Constant.Unmarshal(m, b)
}
func (m *Constant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Constant.Marshal(b, m, deterministic)
}
func (m *Constant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Constant.Merge(m, src)
}
func (m *Constant) XXX_Size() int {
	return xxx_messageInfo_Constant.Size(m)
}
func (m *Constant) XXX_DiscardUnknown() {
	xxx_messageInfo_Constant.DiscardUnknown(m)
}

var xxx_messageInfo_Constant proto.InternalMessageInfo

func (m *Constant) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Constant) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Constant) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Constant) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// Step represents a single unit of work performed by a pipeline.  Every pipeline
// step is based on a StepTemplate defined by the system. Pipeline creators
// override template values to customise the step to their needs.
type Step struct {
	// Type of pipeline this step applies to (from the step template).
	Type Type `protobuf:"varint,1,opt,name=type,proto3,enum=sajari.pipeline.v2.Type" json:"type,omitempty"`
	// Type of step (from the step template).
	StepTypes []StepType `protobuf:"varint,2,rep,packed,name=step_types,json=stepTypes,proto3,enum=sajari.pipeline.v2.StepType" json:"step_types,omitempty"`
	// Identifier of this step (from the step template).
	Identifier string `protobuf:"bytes,3,opt,name=identifier,proto3" json:"identifier,omitempty"`
	// Title of step in this pipeline.
	Title string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	// Description of the step in this pipeline.
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	// List of input parameters used by the step.
	Inputs []*Parameter `protobuf:"bytes,6,rep,name=inputs,proto3" json:"inputs,omitempty"`
	// List of output parameters returned by the step.
	Outputs []*Parameter `protobuf:"bytes,7,rep,name=outputs,proto3" json:"outputs,omitempty"`
	// List of constants used by the step.
	Constants []*Constant `protobuf:"bytes,8,rep,name=constants,proto3" json:"constants,omitempty"`
	// Condition that must pass for the step to be run.
	Condition            string   `protobuf:"bytes,9,opt,name=condition,proto3" json:"condition,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Step) Reset()         { *m = Step{} }
func (m *Step) String() string { return proto.CompactTextString(m) }
func (*Step) ProtoMessage()    {}
func (*Step) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fca4025792f792a, []int{5}
}

func (m *Step) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Step.Unmarshal(m, b)
}
func (m *Step) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Step.Marshal(b, m, deterministic)
}
func (m *Step) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Step.Merge(m, src)
}
func (m *Step) XXX_Size() int {
	return xxx_messageInfo_Step.Size(m)
}
func (m *Step) XXX_DiscardUnknown() {
	xxx_messageInfo_Step.DiscardUnknown(m)
}

var xxx_messageInfo_Step proto.InternalMessageInfo

func (m *Step) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_TYPE_UNSPECIFIED
}

func (m *Step) GetStepTypes() []StepType {
	if m != nil {
		return m.StepTypes
	}
	return nil
}

func (m *Step) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *Step) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Step) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Step) GetInputs() []*Parameter {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *Step) GetOutputs() []*Parameter {
	if m != nil {
		return m.Outputs
	}
	return nil
}

func (m *Step) GetConstants() []*Constant {
	if m != nil {
		return m.Constants
	}
	return nil
}

func (m *Step) GetCondition() string {
	if m != nil {
		return m.Condition
	}
	return ""
}

// ListStepTemplatesRequest is used to request a listing of step templates.
type ListStepTemplatesRequest struct {
	// Type of pipeline steps to list (query/record).
	Type Type `protobuf:"varint,1,opt,name=type,proto3,enum=sajari.pipeline.v2.Type" json:"type,omitempty"`
	// Step types to list (pre/post).
	StepType StepType `protobuf:"varint,2,opt,name=step_type,json=stepType,proto3,enum=sajari.pipeline.v2.StepType" json:"step_type,omitempty"`
	// The maximum number of steps to return.
	PageSize int32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// The `next_page_token` value returned from a previous List request, if any.
	PageToken            string   `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListStepTemplatesRequest) Reset()         { *m = ListStepTemplatesRequest{} }
func (m *ListStepTemplatesRequest) String() string { return proto.CompactTextString(m) }
func (*ListStepTemplatesRequest) ProtoMessage()    {}
func (*ListStepTemplatesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fca4025792f792a, []int{6}
}

func (m *ListStepTemplatesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListStepTemplatesRequest.Unmarshal(m, b)
}
func (m *ListStepTemplatesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListStepTemplatesRequest.Marshal(b, m, deterministic)
}
func (m *ListStepTemplatesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListStepTemplatesRequest.Merge(m, src)
}
func (m *ListStepTemplatesRequest) XXX_Size() int {
	return xxx_messageInfo_ListStepTemplatesRequest.Size(m)
}
func (m *ListStepTemplatesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListStepTemplatesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListStepTemplatesRequest proto.InternalMessageInfo

func (m *ListStepTemplatesRequest) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_TYPE_UNSPECIFIED
}

func (m *ListStepTemplatesRequest) GetStepType() StepType {
	if m != nil {
		return m.StepType
	}
	return StepType_STEP_TYPE_UNSPECIFIED
}

func (m *ListStepTemplatesRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListStepTemplatesRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

// ListStepsResponse contains a list of steps.
type ListStepTemplatesResponse struct {
	// List of steps.
	StepTemplates []*Step `protobuf:"bytes,1,rep,name=step_templates,json=stepTemplates,proto3" json:"step_templates,omitempty"`
	// The next page token.
	NextPageToken        string   `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListStepTemplatesResponse) Reset()         { *m = ListStepTemplatesResponse{} }
func (m *ListStepTemplatesResponse) String() string { return proto.CompactTextString(m) }
func (*ListStepTemplatesResponse) ProtoMessage()    {}
func (*ListStepTemplatesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fca4025792f792a, []int{7}
}

func (m *ListStepTemplatesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListStepTemplatesResponse.Unmarshal(m, b)
}
func (m *ListStepTemplatesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListStepTemplatesResponse.Marshal(b, m, deterministic)
}
func (m *ListStepTemplatesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListStepTemplatesResponse.Merge(m, src)
}
func (m *ListStepTemplatesResponse) XXX_Size() int {
	return xxx_messageInfo_ListStepTemplatesResponse.Size(m)
}
func (m *ListStepTemplatesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListStepTemplatesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListStepTemplatesResponse proto.InternalMessageInfo

func (m *ListStepTemplatesResponse) GetStepTemplates() []*Step {
	if m != nil {
		return m.StepTemplates
	}
	return nil
}

func (m *ListStepTemplatesResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

// GetStepDocumentationRequest
type GetStepTemplateDocumentationRequest struct {
	// Type of pipeline to fetch step for.
	Type Type `protobuf:"varint,1,opt,name=type,proto3,enum=sajari.pipeline.v2.Type" json:"type,omitempty"`
	// Identifier for step template.
	Identifier           string   `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStepTemplateDocumentationRequest) Reset()         { *m = GetStepTemplateDocumentationRequest{} }
func (m *GetStepTemplateDocumentationRequest) String() string { return proto.CompactTextString(m) }
func (*GetStepTemplateDocumentationRequest) ProtoMessage()    {}
func (*GetStepTemplateDocumentationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fca4025792f792a, []int{8}
}

func (m *GetStepTemplateDocumentationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStepTemplateDocumentationRequest.Unmarshal(m, b)
}
func (m *GetStepTemplateDocumentationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStepTemplateDocumentationRequest.Marshal(b, m, deterministic)
}
func (m *GetStepTemplateDocumentationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStepTemplateDocumentationRequest.Merge(m, src)
}
func (m *GetStepTemplateDocumentationRequest) XXX_Size() int {
	return xxx_messageInfo_GetStepTemplateDocumentationRequest.Size(m)
}
func (m *GetStepTemplateDocumentationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStepTemplateDocumentationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStepTemplateDocumentationRequest proto.InternalMessageInfo

func (m *GetStepTemplateDocumentationRequest) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_TYPE_UNSPECIFIED
}

func (m *GetStepTemplateDocumentationRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

// GetStepDocumentationResponse
type GetStepTemplateDocumentationResponse struct {
	StepTemplate         *Step    `protobuf:"bytes,1,opt,name=step_template,json=stepTemplate,proto3" json:"step_template,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStepTemplateDocumentationResponse) Reset()         { *m = GetStepTemplateDocumentationResponse{} }
func (m *GetStepTemplateDocumentationResponse) String() string { return proto.CompactTextString(m) }
func (*GetStepTemplateDocumentationResponse) ProtoMessage()    {}
func (*GetStepTemplateDocumentationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fca4025792f792a, []int{9}
}

func (m *GetStepTemplateDocumentationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStepTemplateDocumentationResponse.Unmarshal(m, b)
}
func (m *GetStepTemplateDocumentationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStepTemplateDocumentationResponse.Marshal(b, m, deterministic)
}
func (m *GetStepTemplateDocumentationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStepTemplateDocumentationResponse.Merge(m, src)
}
func (m *GetStepTemplateDocumentationResponse) XXX_Size() int {
	return xxx_messageInfo_GetStepTemplateDocumentationResponse.Size(m)
}
func (m *GetStepTemplateDocumentationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStepTemplateDocumentationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStepTemplateDocumentationResponse proto.InternalMessageInfo

func (m *GetStepTemplateDocumentationResponse) GetStepTemplate() *Step {
	if m != nil {
		return m.StepTemplate
	}
	return nil
}

func init() {
	proto.RegisterType((*GetPipelineDocumentationRequest)(nil), "sajari.pipeline.v2.GetPipelineDocumentationRequest")
	proto.RegisterType((*GetPipelineDocumentationResponse)(nil), "sajari.pipeline.v2.GetPipelineDocumentationResponse")
	proto.RegisterType((*Steps)(nil), "sajari.pipeline.v2.Steps")
	proto.RegisterType((*Parameter)(nil), "sajari.pipeline.v2.Parameter")
	proto.RegisterType((*Constant)(nil), "sajari.pipeline.v2.Constant")
	proto.RegisterType((*Step)(nil), "sajari.pipeline.v2.Step")
	proto.RegisterType((*ListStepTemplatesRequest)(nil), "sajari.pipeline.v2.ListStepTemplatesRequest")
	proto.RegisterType((*ListStepTemplatesResponse)(nil), "sajari.pipeline.v2.ListStepTemplatesResponse")
	proto.RegisterType((*GetStepTemplateDocumentationRequest)(nil), "sajari.pipeline.v2.GetStepTemplateDocumentationRequest")
	proto.RegisterType((*GetStepTemplateDocumentationResponse)(nil), "sajari.pipeline.v2.GetStepTemplateDocumentationResponse")
}

func init() {
	proto.RegisterFile("sajari/pipeline/v2/documentation.proto", fileDescriptor_8fca4025792f792a)
}

var fileDescriptor_8fca4025792f792a = []byte{
	// 761 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0x41, 0x6f, 0xd3, 0x4a,
	0x10, 0x96, 0x93, 0x38, 0x8d, 0x27, 0x4d, 0x9f, 0xde, 0xaa, 0x07, 0x37, 0xaf, 0x7d, 0x0d, 0x2e,
	0xaa, 0x7a, 0x68, 0x1d, 0x29, 0x05, 0x95, 0x12, 0x01, 0x12, 0x20, 0x55, 0x48, 0x1c, 0x2a, 0xb7,
	0xe2, 0xc0, 0x25, 0x72, 0x93, 0x69, 0xb4, 0x25, 0xb1, 0x17, 0xef, 0xba, 0xa2, 0x3d, 0xc3, 0x0f,
	0x40, 0xdc, 0x90, 0xf8, 0x2d, 0xfc, 0x2d, 0x8e, 0xc8, 0xbb, 0x5e, 0x37, 0x69, 0xec, 0xa6, 0x81,
	0xdb, 0x7a, 0x76, 0xbe, 0xfd, 0x66, 0xbe, 0x6f, 0x36, 0x1b, 0xd8, 0xe6, 0xfe, 0x85, 0x1f, 0xd1,
	0x36, 0xa3, 0x0c, 0x47, 0x34, 0xc0, 0xf6, 0x65, 0xa7, 0x3d, 0x08, 0xfb, 0xf1, 0x18, 0x03, 0xe1,
	0x0b, 0x1a, 0x06, 0x2e, 0x8b, 0x42, 0x11, 0x12, 0xa2, 0xf2, 0x5c, 0x9d, 0xe7, 0x5e, 0x76, 0x9a,
	0x0f, 0x72, 0xb0, 0xd9, 0xbe, 0x84, 0x35, 0x37, 0x87, 0x61, 0x38, 0x1c, 0x61, 0x5b, 0x7e, 0x9d,
	0xc5, 0xe7, 0x6d, 0x41, 0xc7, 0xc8, 0x85, 0x3f, 0x66, 0x2a, 0xc1, 0xf1, 0x61, 0xf3, 0x08, 0xc5,
	0x71, 0x8a, 0x7a, 0x3d, 0xc9, 0xec, 0xe1, 0xc7, 0x18, 0xb9, 0x20, 0xcf, 0xa1, 0xa6, 0x4f, 0xb5,
	0x8d, 0x96, 0xb1, 0x53, 0xef, 0x38, 0xee, 0x6c, 0x35, 0xee, 0xe9, 0x15, 0xc3, 0x37, 0x03, 0x0c,
	0x04, 0x3d, 0xa7, 0x18, 0x79, 0x19, 0xc6, 0xf9, 0x55, 0x82, 0x56, 0x31, 0x07, 0x67, 0x61, 0xc0,
	0xf1, 0x6f, 0x49, 0xc8, 0x2a, 0x98, 0x82, 0x8a, 0x11, 0xda, 0xa5, 0x96, 0xb1, 0x63, 0x79, 0xea,
	0x83, 0xb4, 0xa0, 0x3e, 0x40, 0xde, 0x8f, 0x28, 0x4b, 0xc8, 0xec, 0xb2, 0xdc, 0x9b, 0x0c, 0x91,
	0x36, 0x98, 0x5c, 0x20, 0xe3, 0x76, 0xa5, 0x55, 0xde, 0xa9, 0x77, 0xd6, 0xf2, 0x48, 0x4f, 0x92,
	0x04, 0x4f, 0xe5, 0x91, 0xc7, 0x50, 0xa5, 0x01, 0x8b, 0x05, 0xb7, 0x4d, 0x89, 0xd8, 0xc8, 0x43,
	0x1c, 0xfb, 0x91, 0x3f, 0x46, 0x81, 0x91, 0x97, 0x26, 0x93, 0x03, 0x58, 0x0a, 0x63, 0x21, 0x71,
	0xd5, 0xfb, 0xe0, 0x74, 0x36, 0xe9, 0x42, 0xbd, 0x1f, 0xa1, 0x2f, 0xb0, 0x97, 0x58, 0x67, 0x2f,
	0x49, 0x6d, 0x9a, 0xae, 0xf2, 0xd5, 0xd5, 0xbe, 0xba, 0xa7, 0xda, 0x57, 0x0f, 0x54, 0x7a, 0x12,
	0x70, 0x22, 0x30, 0x65, 0xf1, 0xe4, 0x10, 0xac, 0xa4, 0xfc, 0x9e, 0xb8, 0x62, 0x4a, 0xdf, 0x95,
	0xce, 0x7a, 0x51, 0xab, 0x89, 0xc6, 0x5e, 0x8d, 0xa7, 0x2b, 0xe2, 0x6a, 0x85, 0x4a, 0xb2, 0x6e,
	0xbb, 0x08, 0x96, 0x0a, 0xe4, 0x7c, 0x37, 0xc0, 0xca, 0xfa, 0x20, 0xff, 0x03, 0xd0, 0xcc, 0x2f,
	0xc9, 0x6c, 0x79, 0x13, 0x11, 0x42, 0xa0, 0x12, 0xf8, 0x63, 0x6d, 0x9b, 0x5c, 0x27, 0x31, 0x59,
	0xa7, 0xb2, 0x4b, 0xae, 0x6f, 0x3b, 0x59, 0x99, 0x75, 0x72, 0x0b, 0x1a, 0x03, 0x3c, 0xf7, 0xe3,
	0x91, 0xe8, 0x5d, 0xfa, 0xa3, 0x18, 0x6d, 0x53, 0xe6, 0x2c, 0xa7, 0xc1, 0x77, 0x49, 0xcc, 0xb9,
	0x80, 0xda, 0xab, 0x30, 0xe0, 0xc2, 0x0f, 0x44, 0x46, 0x6d, 0xe4, 0x50, 0x97, 0x8a, 0xa9, 0x73,
	0x86, 0x68, 0x15, 0x4c, 0x45, 0xa9, 0xca, 0x52, 0x1f, 0xce, 0xb7, 0x32, 0x54, 0x12, 0x61, 0xc8,
	0x6e, 0x7a, 0xa8, 0xd2, 0xdd, 0x2e, 0x9a, 0xeb, 0x94, 0xae, 0x0b, 0x90, 0x59, 0xa5, 0x44, 0x9f,
	0xe7, 0x95, 0xa5, 0xbd, 0xe2, 0xb7, 0xe4, 0x2e, 0xcf, 0xc8, 0x9d, 0x5d, 0x93, 0xca, 0x1d, 0xd7,
	0xc4, 0x9c, 0xed, 0xf0, 0x66, 0xea, 0xab, 0x7f, 0x38, 0xf5, 0x4b, 0x0b, 0x4d, 0xfd, 0x53, 0xb0,
	0xfa, 0xa9, 0x4f, 0xdc, 0xae, 0x49, 0x68, 0xae, 0x06, 0xda, 0x4c, 0xef, 0x26, 0x9d, 0xac, 0x4b,
	0xec, 0x80, 0xca, 0x5e, 0x2c, 0xd9, 0xcb, 0x4d, 0xc0, 0xf9, 0x69, 0x80, 0xfd, 0x96, 0x72, 0x21,
	0xd5, 0xc3, 0x31, 0x1b, 0xf9, 0x02, 0xb9, 0xfe, 0xa9, 0x5b, 0xcc, 0xa9, 0xa9, 0x4b, 0x55, 0x5a,
	0xe8, 0x52, 0xfd, 0x07, 0x16, 0xf3, 0x87, 0xd8, 0xe3, 0xf4, 0x5a, 0xcd, 0xb9, 0xe9, 0xd5, 0x92,
	0xc0, 0x09, 0xbd, 0x46, 0xb2, 0x01, 0x20, 0x37, 0x45, 0xf8, 0x01, 0xf5, 0xa8, 0xcb, 0xf4, 0xd3,
	0x24, 0xe0, 0x7c, 0x36, 0x60, 0x2d, 0xa7, 0x83, 0xf4, 0x87, 0xf4, 0x05, 0xac, 0xa8, 0xa2, 0xf4,
	0x8e, 0x6d, 0xcc, 0xb9, 0xb7, 0x0d, 0x3e, 0x79, 0x10, 0xd9, 0x86, 0x7f, 0x02, 0xfc, 0x24, 0x7a,
	0x13, 0x25, 0xa8, 0xdb, 0xd0, 0x48, 0xc2, 0xc7, 0x59, 0x19, 0x1c, 0xb6, 0x8e, 0x70, 0xaa, 0x88,
	0xdc, 0xd7, 0x63, 0x31, 0x49, 0xa7, 0xe7, 0xb7, 0x74, 0x7b, 0x7e, 0x1d, 0x84, 0x87, 0x77, 0x93,
	0xa6, 0x2a, 0x3c, 0x83, 0xc6, 0x94, 0x0a, 0xe9, 0x9b, 0x52, 0x2c, 0xc2, 0xf2, 0xa4, 0x08, 0x9d,
	0x1f, 0x65, 0x68, 0x4c, 0x1d, 0x4c, 0xbe, 0x18, 0x60, 0x17, 0x3d, 0x62, 0x64, 0x3f, 0xef, 0xd8,
	0x39, 0xcf, 0x6a, 0xf3, 0xd1, 0x62, 0xa0, 0xb4, 0x31, 0x06, 0xff, 0xce, 0x78, 0x4f, 0x76, 0xf3,
	0x8e, 0x2a, 0x1a, 0xf2, 0xe6, 0xde, 0x3d, 0xb3, 0x53, 0xc6, 0xaf, 0x06, 0xac, 0xdf, 0xa5, 0x39,
	0x39, 0x28, 0x68, 0x64, 0xde, 0x68, 0x34, 0x9f, 0x2c, 0x0e, 0x54, 0x35, 0xbd, 0xec, 0xbe, 0x3f,
	0xec, 0x87, 0x03, 0xd4, 0xf8, 0x7e, 0x38, 0x56, 0xff, 0x70, 0x86, 0x18, 0xec, 0x0d, 0xc3, 0xf6,
	0xec, 0xff, 0xa2, 0xae, 0x5e, 0xb3, 0xb3, 0xb3, 0xaa, 0x4c, 0xdd, 0xff, 0x1d, 0x00, 0x00, 0xff,
	0xff, 0x97, 0xef, 0xfe, 0xca, 0x7b, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DocumentationClient is the client API for Documentation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DocumentationClient interface {
	// GetPipelineDocumentation.
	GetPipelineDocumentation(ctx context.Context, in *GetPipelineDocumentationRequest, opts ...grpc.CallOption) (*GetPipelineDocumentationResponse, error)
	// List step templates that can be used in creating pipelines.
	ListStepTemplates(ctx context.Context, in *ListStepTemplatesRequest, opts ...grpc.CallOption) (*ListStepTemplatesResponse, error)
	// Get step template documentation.
	GetStepTemplateDocumentation(ctx context.Context, in *GetStepTemplateDocumentationRequest, opts ...grpc.CallOption) (*GetStepTemplateDocumentationResponse, error)
}

type documentationClient struct {
	cc *grpc.ClientConn
}

func NewDocumentationClient(cc *grpc.ClientConn) DocumentationClient {
	return &documentationClient{cc}
}

func (c *documentationClient) GetPipelineDocumentation(ctx context.Context, in *GetPipelineDocumentationRequest, opts ...grpc.CallOption) (*GetPipelineDocumentationResponse, error) {
	out := new(GetPipelineDocumentationResponse)
	err := c.cc.Invoke(ctx, "/sajari.pipeline.v2.Documentation/GetPipelineDocumentation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentationClient) ListStepTemplates(ctx context.Context, in *ListStepTemplatesRequest, opts ...grpc.CallOption) (*ListStepTemplatesResponse, error) {
	out := new(ListStepTemplatesResponse)
	err := c.cc.Invoke(ctx, "/sajari.pipeline.v2.Documentation/ListStepTemplates", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentationClient) GetStepTemplateDocumentation(ctx context.Context, in *GetStepTemplateDocumentationRequest, opts ...grpc.CallOption) (*GetStepTemplateDocumentationResponse, error) {
	out := new(GetStepTemplateDocumentationResponse)
	err := c.cc.Invoke(ctx, "/sajari.pipeline.v2.Documentation/GetStepTemplateDocumentation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DocumentationServer is the server API for Documentation service.
type DocumentationServer interface {
	// GetPipelineDocumentation.
	GetPipelineDocumentation(context.Context, *GetPipelineDocumentationRequest) (*GetPipelineDocumentationResponse, error)
	// List step templates that can be used in creating pipelines.
	ListStepTemplates(context.Context, *ListStepTemplatesRequest) (*ListStepTemplatesResponse, error)
	// Get step template documentation.
	GetStepTemplateDocumentation(context.Context, *GetStepTemplateDocumentationRequest) (*GetStepTemplateDocumentationResponse, error)
}

// UnimplementedDocumentationServer can be embedded to have forward compatible implementations.
type UnimplementedDocumentationServer struct {
}

func (*UnimplementedDocumentationServer) GetPipelineDocumentation(ctx context.Context, req *GetPipelineDocumentationRequest) (*GetPipelineDocumentationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPipelineDocumentation not implemented")
}
func (*UnimplementedDocumentationServer) ListStepTemplates(ctx context.Context, req *ListStepTemplatesRequest) (*ListStepTemplatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListStepTemplates not implemented")
}
func (*UnimplementedDocumentationServer) GetStepTemplateDocumentation(ctx context.Context, req *GetStepTemplateDocumentationRequest) (*GetStepTemplateDocumentationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStepTemplateDocumentation not implemented")
}

func RegisterDocumentationServer(s *grpc.Server, srv DocumentationServer) {
	s.RegisterService(&_Documentation_serviceDesc, srv)
}

func _Documentation_GetPipelineDocumentation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPipelineDocumentationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentationServer).GetPipelineDocumentation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sajari.pipeline.v2.Documentation/GetPipelineDocumentation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentationServer).GetPipelineDocumentation(ctx, req.(*GetPipelineDocumentationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Documentation_ListStepTemplates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStepTemplatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentationServer).ListStepTemplates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sajari.pipeline.v2.Documentation/ListStepTemplates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentationServer).ListStepTemplates(ctx, req.(*ListStepTemplatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Documentation_GetStepTemplateDocumentation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStepTemplateDocumentationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentationServer).GetStepTemplateDocumentation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sajari.pipeline.v2.Documentation/GetStepTemplateDocumentation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentationServer).GetStepTemplateDocumentation(ctx, req.(*GetStepTemplateDocumentationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Documentation_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sajari.pipeline.v2.Documentation",
	HandlerType: (*DocumentationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPipelineDocumentation",
			Handler:    _Documentation_GetPipelineDocumentation_Handler,
		},
		{
			MethodName: "ListStepTemplates",
			Handler:    _Documentation_ListStepTemplates_Handler,
		},
		{
			MethodName: "GetStepTemplateDocumentation",
			Handler:    _Documentation_GetStepTemplateDocumentation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sajari/pipeline/v2/documentation.proto",
}
