// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sajari/pipeline/v2/pipeline.proto

package pipelinepb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Type of pipeline.
type Type int32

const (
	// Not specified.
	Type_TYPE_UNSPECIFIED Type = 0
	// Query pipeline.
	Type_QUERY_PIPELINE Type = 1
	// Record pipeline.
	Type_RECORD_PIPELINE Type = 2
)

var Type_name = map[int32]string{
	0: "TYPE_UNSPECIFIED",
	1: "QUERY_PIPELINE",
	2: "RECORD_PIPELINE",
}

var Type_value = map[string]int32{
	"TYPE_UNSPECIFIED": 0,
	"QUERY_PIPELINE":   1,
	"RECORD_PIPELINE":  2,
}

func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}

func (Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e40d0374bbcc30b3, []int{0}
}

// Type of step.
type StepType int32

const (
	// Unspecified.
	StepType_STEP_TYPE_UNSPECIFIED StepType = 0
	// Pre steps are run before an engine operation,
	// for example Search, CreateRecord, etc...
	StepType_PRE_STEP StepType = 1
	// Post steps are run after an engine operation,
	// for example Search, CreateRecord, etc...
	StepType_POST_STEP StepType = 2
)

var StepType_name = map[int32]string{
	0: "STEP_TYPE_UNSPECIFIED",
	1: "PRE_STEP",
	2: "POST_STEP",
}

var StepType_value = map[string]int32{
	"STEP_TYPE_UNSPECIFIED": 0,
	"PRE_STEP":              1,
	"POST_STEP":             2,
}

func (x StepType) String() string {
	return proto.EnumName(StepType_name, int32(x))
}

func (StepType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e40d0374bbcc30b3, []int{1}
}

type TypeIdentifer struct {
	Type                 Type        `protobuf:"varint,1,opt,name=type,proto3,enum=sajari.pipeline.v2.Type" json:"type,omitempty"`
	Identifier           *Identifier `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TypeIdentifer) Reset()         { *m = TypeIdentifer{} }
func (m *TypeIdentifer) String() string { return proto.CompactTextString(m) }
func (*TypeIdentifer) ProtoMessage()    {}
func (*TypeIdentifer) Descriptor() ([]byte, []int) {
	return fileDescriptor_e40d0374bbcc30b3, []int{0}
}

func (m *TypeIdentifer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TypeIdentifer.Unmarshal(m, b)
}
func (m *TypeIdentifer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TypeIdentifer.Marshal(b, m, deterministic)
}
func (m *TypeIdentifer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TypeIdentifer.Merge(m, src)
}
func (m *TypeIdentifer) XXX_Size() int {
	return xxx_messageInfo_TypeIdentifer.Size(m)
}
func (m *TypeIdentifer) XXX_DiscardUnknown() {
	xxx_messageInfo_TypeIdentifer.DiscardUnknown(m)
}

var xxx_messageInfo_TypeIdentifer proto.InternalMessageInfo

func (m *TypeIdentifer) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_TYPE_UNSPECIFIED
}

func (m *TypeIdentifer) GetIdentifier() *Identifier {
	if m != nil {
		return m.Identifier
	}
	return nil
}

// Identifier is used to specify a pipeline.
type Identifier struct {
	// Name uniquely defines a pipeline.
	// [a-z][a-z0-9-]*
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Version is the unique identifier.
	Version              string   `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Identifier) Reset()         { *m = Identifier{} }
func (m *Identifier) String() string { return proto.CompactTextString(m) }
func (*Identifier) ProtoMessage()    {}
func (*Identifier) Descriptor() ([]byte, []int) {
	return fileDescriptor_e40d0374bbcc30b3, []int{1}
}

func (m *Identifier) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Identifier.Unmarshal(m, b)
}
func (m *Identifier) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Identifier.Marshal(b, m, deterministic)
}
func (m *Identifier) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Identifier.Merge(m, src)
}
func (m *Identifier) XXX_Size() int {
	return xxx_messageInfo_Identifier.Size(m)
}
func (m *Identifier) XXX_DiscardUnknown() {
	xxx_messageInfo_Identifier.DiscardUnknown(m)
}

var xxx_messageInfo_Identifier proto.InternalMessageInfo

func (m *Identifier) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Identifier) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func init() {
	proto.RegisterEnum("sajari.pipeline.v2.Type", Type_name, Type_value)
	proto.RegisterEnum("sajari.pipeline.v2.StepType", StepType_name, StepType_value)
	proto.RegisterType((*TypeIdentifer)(nil), "sajari.pipeline.v2.TypeIdentifer")
	proto.RegisterType((*Identifier)(nil), "sajari.pipeline.v2.Identifier")
}

func init() { proto.RegisterFile("sajari/pipeline/v2/pipeline.proto", fileDescriptor_e40d0374bbcc30b3) }

var fileDescriptor_e40d0374bbcc30b3 = []byte{
	// 299 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xcd, 0x4f, 0xf2, 0x40,
	0x10, 0xc6, 0xdf, 0xf2, 0x12, 0x85, 0x51, 0xb0, 0x19, 0x35, 0xa9, 0x17, 0x83, 0x9c, 0x08, 0xd1,
	0x36, 0xa9, 0x27, 0x25, 0xf1, 0x00, 0xac, 0xc9, 0x26, 0x06, 0xd6, 0x6d, 0x39, 0xe0, 0xa5, 0xe1,
	0x63, 0x25, 0x6b, 0xa4, 0xbb, 0x29, 0x0d, 0x09, 0x07, 0xff, 0x77, 0xd3, 0x6d, 0x5a, 0x4c, 0xe0,
	0xf6, 0xcc, 0x33, 0xcf, 0x6f, 0xf6, 0x63, 0xe0, 0x6e, 0x33, 0xfb, 0x9a, 0x25, 0xd2, 0xd3, 0x52,
	0x8b, 0x6f, 0x19, 0x0b, 0x6f, 0xeb, 0x97, 0xda, 0xd5, 0x89, 0x4a, 0x15, 0x62, 0x1e, 0x71, 0x4b,
	0x7b, 0xeb, 0xb7, 0x7f, 0xa0, 0x11, 0xee, 0xb4, 0xa0, 0x4b, 0x11, 0xa7, 0xf2, 0x53, 0x24, 0x78,
	0x0f, 0xd5, 0x74, 0xa7, 0x85, 0x63, 0xb5, 0xac, 0x4e, 0xd3, 0x77, 0xdc, 0x43, 0xc6, 0xcd, 0x00,
	0x6e, 0x52, 0xf8, 0x02, 0x20, 0x73, 0x54, 0x8a, 0xc4, 0xa9, 0xb4, 0xac, 0xce, 0x99, 0x7f, 0x7b,
	0x8c, 0xa1, 0x65, 0x8a, 0xff, 0x21, 0xda, 0xcf, 0x00, 0xfb, 0x0e, 0x22, 0x54, 0xe3, 0xd9, 0x3a,
	0x3f, 0xbb, 0xce, 0x8d, 0x46, 0x07, 0x4e, 0xb7, 0x22, 0xd9, 0x48, 0x15, 0x3b, 0xff, 0x8d, 0x5d,
	0x94, 0x5d, 0x02, 0xd5, 0xec, 0x26, 0x78, 0x05, 0x76, 0x38, 0x65, 0x24, 0x9a, 0x8c, 0x02, 0x46,
	0x06, 0xf4, 0x95, 0x92, 0xa1, 0xfd, 0x0f, 0x11, 0x9a, 0xef, 0x13, 0xc2, 0xa7, 0x11, 0xa3, 0x8c,
	0xbc, 0xd1, 0x11, 0xb1, 0x2d, 0xbc, 0x84, 0x0b, 0x4e, 0x06, 0x63, 0x3e, 0xdc, 0x9b, 0x95, 0x6e,
	0x1f, 0x6a, 0x41, 0x2a, 0xb4, 0x19, 0x75, 0x03, 0xd7, 0x41, 0x48, 0x58, 0x74, 0x64, 0xde, 0x39,
	0xd4, 0x18, 0x27, 0x51, 0xd6, 0xb6, 0x2d, 0x6c, 0x40, 0x9d, 0x8d, 0x83, 0x30, 0x2f, 0x2b, 0xfd,
	0xde, 0xc7, 0xd3, 0x42, 0x2d, 0x45, 0xf1, 0xf0, 0x85, 0x5a, 0x7b, 0xe6, 0xcb, 0x57, 0x22, 0x7e,
	0x58, 0x29, 0xef, 0x70, 0x35, 0xbd, 0x42, 0xeb, 0xf9, 0xfc, 0xc4, 0x44, 0x1f, 0x7f, 0x03, 0x00,
	0x00, 0xff, 0xff, 0x9d, 0x06, 0xb9, 0xd6, 0xc2, 0x01, 0x00, 0x00,
}
